version: "3.9"
services:
  client:
    build:
      context: .
      dockerfile: "client/Dockerfile"
    environment:
      - SERVER_PORT=${SERVER_PORT}
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    # depends_on:
    #   - "server"