name: Build Docker Image

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo $ENGINE_PATH
    - run: docker-compose build