name: buildServer

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: >
        cd server
        && npm install --silent
        && echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env.production.local
        && npm run start